AllCops:
  NewCops: enable
  TargetRubyVersion: 2.0

Gemspec/DevelopmentDependencies:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 80
  AllowedPatterns:
    - "spec.description\\s="

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: same_line

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/BlockLength:
  Exclude:
    - "**/spec/**/*"
    - "**/*.gemspec"

Metrics/ClassLength:
  Max: 120

Metrics/CyclomaticComplexity:
  AllowedMethods:
    - keypress

Metrics/MethodLength:
  AllowedMethods:
    - split_into_slides

Metrics/PerceivedComplexity:
  Max: 5
  AllowedMethods:
    - convert_to_array

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  PreferredName: err

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/BlockDelimiters:
  AllowedMethods:
    - expect
    - let

Style/CommentedKeyword:
  Enabled: false

Style/FetchEnvVar:
  AllowedVars:
    - COVERAGE

Style/IfUnlessModifier:
  Enabled: false

Style/LambdaCall:
  EnforcedStyle: braces

Style/ParallelAssignment:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
